# Generated by Django 6.0.7 on 2026-07-30 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='auther',
            new_name='author',
        ),
    ]
