# Generated by Django 6.0.7 on 2026-08-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_tag_news_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'тег', 'verbose_name_plural': 'теги'},
        ),
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(related_name='news', to='main.tag', verbose_name='теги'),
        ),
    ]
