# Generated by Django 6.0.7 on 2026-08-11 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_tag_options_alter_news_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name='whatsapp')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='telegram')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='instagram')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='facebook')),
                ('news', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='main.news', verbose_name='новость')),
            ],
            options={
                'verbose_name': 'ссылка новостей',
                'verbose_name_plural': 'ссылки новостей',
            },
        ),
    ]
