# Generated by Django 6.0.7 on 2026-08-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_newslinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='дата обновления'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата добавления'),
        ),
    ]
